### ISSUE TITLE
SFMTools.py error.

### ISSUE THREAD

**Issue by davidbaines** [pconstrictor/PySfm#1]
PS C:\Users\David\documents\py\SFMUtils> py -3 SFMTools.py -h
Running under Python 3.6.0
Traceback (most recent call last):
  File "SFMTools.py", line 573, in <module>
    class NumStripper:
  File "SFMTools.py", line 575, in NumStripper
    re_strip_sense_num = re.compile(r"\s+\d+$", flags = re.LOCALE | re.MULTILINE | re.UNICODE)
  File "C:\Users\David\AppData\Local\Programs\Python\Python36-32\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "C:\Users\David\AppData\Local\Programs\Python\Python36-32\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\David\AppData\Local\Programs\Python\Python36-32\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\David\AppData\Local\Programs\Python\Python36-32\lib\sre_parse.py", line 866, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "C:\Users\David\AppData\Local\Programs\Python\Python36-32\lib\sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
PS C:\Users\David\documents\willie\py\SFMUtils>

This is in Windows 10 Powershell and the error occurs with or without an input file specified.  Preventing me from running the program.

**Comment by davidbaines** [comment]
My mistake sorry.  It looks as though I has accidentally modified the code in SFMTools.py
